bash/*: apply shellcheck

diff --git a/bash/bash_functions b/bash/bash_functions
--- a/bash/bash_functions
+++ b/bash/bash_functions
@@ -2,7 +2,7 @@
 
 function _anniversary_helper
 {
-    local -r basedate=${1:?Usage: $FUNCNAME \'date(YYYY, mm, dd)\'}
+    local -r basedate=${1:?Usage: ${FUNCNAME[0]} \'date(YYYY, mm, dd)\'}
 
     python << EOL -
 from datetime import date
@@ -24,16 +24,16 @@ function sunset-anniversary
 # Convert Markdown to reStructuredText
 function convert_md_to_rst
 {
-    local -r input="${1:?Usage: $FUNCNAME MARKDOWN_PATH}"
+    local -r input="${1:?Usage: ${FUNCNAME[0]} MARKDOWN_PATH}"
     local -r output="${input%.md}.rst"
-    local -r pandoc_opts="
+    local -ar pandoc_opts=(
         --strip-comments
         --shift-heading-level-by=-1
         --columns=80
         --wrap=preserve
         --to rst
-        "
-    pandoc $pandoc_opts -o "$output" "$input"
+    )
+    pandoc "${pandoc_opts[@]}" -o "$output" "$input"
 }
 
 # Convert MP4 video to MP3 audio
@@ -44,19 +44,18 @@ function convert_mp3
         return
     fi
 
-    local -r ffmpeg_global_options="-loglevel error -y"
-    local -r ffmpeg_input_options=""
-    local -r ffmpeg_output_options="-qscale:a 0 -map a"
+    local -ar ffmpeg_global_options=(-loglevel error -y)
+    local -ar ffmpeg_input_options=()
+    local -ar ffmpeg_output_options=(-qscale:a 0 -map a)
 
     for i in "$@";
     do
         local -r input="$i"
         local -r output="${input%.*}.mp3"
         echo "Processing ${input}..." >&2
-        ffmpeg $ffmpeg_global_options \
-            $ffmpeg_input_options -i "$input" \
-            $ffmpeg_output_options "$output"
-        if [[ $? != 0 ]]; then
+        if ! ffmpeg "${ffmpeg_global_options[@]}" \
+            "${ffmpeg_input_options[@]}" -i "$input" \
+            "${ffmpeg_output_options[@]}" "$output" ; then
             echo "Error: $output is not generated" >&2
             continue
         fi
@@ -68,10 +67,10 @@ function convert_mp3
 # The core function for image-resize-xxxx family
 function _image-resize
 {
-    local -r magick_options="-resize $1 -define preserve-timestamp=true"
+    local -ar magick_options=(-resize "$1" -define preserve-timestamp=true)
     shift
     # Use ImageMagick 7
-    magick mogrify $magick_options "$@"
+    magick mogrify "${magick_options[@]}" "$@"
 }
 
 # Resize image to fit within 854x480 dots
@@ -95,18 +94,20 @@ function image-resize-fullhd
 # For uploading to Twitter
 function video-optimize
 {
-    local -r input="${1:?Usage: $FUNCNAME INPUT_VIDEO_PATH}"
+    local -r input="${1:?Usage: ${FUNCNAME[0]} INPUT_VIDEO_PATH}"
 
-    local -r ffmpeg_global_options="-loglevel error -y"
-    local -r ffmpeg_input_options=""
-    local -r ffmpeg_output_options="
+    local -ar ffmpeg_global_options=(-loglevel error -y)
+    local -ar ffmpeg_input_options=()
+    local -ar ffmpeg_output_options=(
         -c:v libx264 -pix_fmt yuv420p
         -c:a aac -vb 1M -minrate 1M -maxrate 1M -bufsize 1M
-        -ar 44100 -ac 2 -r 30"
+        -ar 44100 -ac 2 -r 30
+    )
 
-    local output="$(mktemp --tmpdir -u --suffix=.mp4 XXXXXXXXX)"
-    ffmpeg $ffmpeg_global_options -i "$input" $ffmpeg_output_options $output
-    if [[ $? != 0 ]]; then
+    output="$(mktemp --tmpdir -u --suffix=.mp4 XXXXXXXXX)"
+    local -r output
+    if ! ffmpeg "${ffmpeg_global_options[@]}" \
+        -i "$input" "${ffmpeg_output_options[@]}" "$output" ; then
         echo "Error: $input conversion failed" >&2
         rm -f "$output"
         return 1
@@ -114,19 +115,19 @@ function video-optimize
 
     touch -r "$input" "$output"
     rm -f "$input"
-    mv $output "$input"
+    mv "$output" "$input"
 }
 
 function video-duration
 {
-    local -r input="${1:?Usage: $FUNCNAME INPUT_VIDEO_PATH}"
+    local -r input="${1:?Usage: ${FUNCNAME[0]} INPUT_VIDEO_PATH}"
 
-    local -r ffprobe_options="
+    local -ar ffprobe_options=(
         -v error -show_entries format=duration
         -of default=noprint_wrappers=1:nokey=1
-        "
+    )
 
-    ffprobe $ffprobe_options "$input"
+    ffprobe "${ffprobe_options[@]}" "$input"
 }
 
 # TODO: wrap drawtext
@@ -144,7 +145,7 @@ function video-duration
 # https://superuser.com/questions/1739162/how-to-fade-from-one-video-to-another-in-ffmpeg-both-audio-and-video
 function video-xfade-naive
 {
-    local -r usage="Usage: $FUNCNAME [-d DURATION] INPUT_VIDEO_PATH0 INPUT_VIDEO_PATH1"
+    local -r usage="Usage: ${FUNCNAME[0]} [-d DURATION] INPUT_VIDEO_PATH0 INPUT_VIDEO_PATH1"
 
     local duration=1
     local OPTIND
@@ -156,7 +157,7 @@ function video-xfade-naive
            duration="${OPTARG}"
            ;;
          *)
-           echo $usage
+           echo "$usage"
            return 1
            ;;
       esac
@@ -167,11 +168,11 @@ function video-xfade-naive
     local -r input1="${2:?${usage}}"
     local -r output=xfade.mp4
 
-    local -r ffmpeg_global_options="-v error -y -hide_banner"
-    local -r trim=$(video-duration ${input0})
-    local -r offset=$(echo $trim - $duration | bc)
+    local -ar ffmpeg_global_options=(-v error -y -hide_banner)
+    local -r trim="$(video-duration "${input0}")"
+    local -r offset="$(echo "$trim" - "$duration" | bc)"
 
-    ffmpeg $ffmpeg_global_options \
+    ffmpeg "${ffmpeg_global_options[@]}" \
         -i "${input0}" -i "${input1}" -filter_complex "
         [0:v]setpts=PTS,settb=AVTB,fps=30[0v];
         [1:v]setpts=PTS,settb=AVTB,fps=30[1v];
@@ -184,26 +185,33 @@ function video-xfade-naive
 # Fade out the last second of the video.
 function video-fadeout
 {
-    local input="${1:?Usage: $FUNCNAME INPUT_VIDEO_PATH}"
+    local input="${1:?Usage: ${FUNCNAME[0]} INPUT_VIDEO_PATH}"
 
     # duration of fade out
     local fade_duration=${2:-1}
 
-    local ffmpeg_global_options="-loglevel error -y"
+    local ffmpeg_global_options=(-loglevel error -y)
 
-    local video_duration=$(video-duration ${input})
-    local output="${input%.*}-faded.${input#*.}"
+    video_duration=$(video-duration "${input}")
+    local -r video_duration
+    local -r output="${input%.*}-faded.${input#*.}"
 
     # from where to fade out
-    local st=$(echo "$video_duration - $fade_duration" | bc)
+    st=$(echo "$video_duration - $fade_duration" | bc)
+    local -r st
 
-    local -r ffmpeg_input_options=""
-    local -r ffmpeg_output_options="
+    local -ar ffmpeg_input_options=()
+    local -ar ffmpeg_output_options=(
+         -c:v libx264 -pix_fmt yuv420p
+         -c:a aac -vb 1M -minrate 1M -maxrate 1M -bufsize 1M
+         -ar 44100 -ac 2 -r 30
+         -vf "fade=t=out:st=$st:d=$fade_duration"
+         -af "afade=t=out:st=$st:d=$fade_duration"
         -vf "fade=t=out:st=$st:d=$fade_duration"
         -af "afade=t=out:st=$st:d=$fade_duration"
-        "
+    )
 
-    ffmpeg $ffmpeg_global_options -i "$input" $ffmpeg_output_options "$output"
+    ffmpeg "${ffmpeg_global_options[@]}" -i "$input" "${ffmpeg_output_options[@]}" "$output"
     touch -r "$input" "$output"
 }
 
@@ -211,69 +219,73 @@ function video-fadeout
 function video-preview
 {
     if [[ -t 0 ]]; then
-        local -r input="${1:?Usage: $FUNCNAME INPUT_VIDEO_PATH}"
+        local -r input="${1:?Usage: ${FUNCNAME[0]} INPUT_VIDEO_PATH}"
     else
         local -r input="-"
     fi
 
-    local -r ffplay_global_options="-v error -hide_banner"
-    local -r ffplay_input_options="-autoexit -x 240 -y 320"
-    ffplay $ffplay_global_options $ffplay_input_options "$input"
+    local -ar ffplay_global_options=(-v error -hide_banner)
+    local -ar ffplay_input_options=(-autoexit -x 240 -y 320)
+    ffplay "${ffplay_global_options[@]}" "${ffplay_input_options[@]}" "$input"
 }
 
 # A variant of video-optimize
 function twitter-merge-video-audio
 {
-    local -r usage="Usage: $FUNCNAME VIDEO_PATH AUDIO_PATH OUTPUT_PATH"
+    local -r usage="Usage: ${FUNCNAME[0]} VIDEO_PATH AUDIO_PATH OUTPUT_PATH"
     local -r input_video="${1:?$usage}"
     local -r input_audio="${2:?$usage}"
     local -r output="${3:?$usage}"
 
-    local -r ffmpeg_global_options="-loglevel error -y"
-    local -r ffmpeg_output_options="
+    local -ar ffmpeg_global_options=(-loglevel error -y)
+    local -ar ffmpeg_output_options=(
         -c:v libx264 -pix_fmt yuv420p
         -c:a aac -vb 1M -minrate 1M -maxrate 1M -bufsize 1M
-        -ar 44100 -ac 2 -r 30"
+        -ar 44100 -ac 2 -r 30)
 
-    ffmpeg $ffmpeg_global_options \
+    ffmpeg "${ffmpeg_global_options[@]}" \
         -i "$input_video" -i "$input_audio" \
-        -map 0:v -map 1:a $ffmpeg_output_options "$output"
+        -map 0:v -map 1:a "${ffmpeg_output_options[@]}" "$output"
 }
 
 # Download an audio file (mp3) from YouTube
 function youtube-download-audio
 {
-    local -r video_url="${1:?Usage: $FUNCNAME VIDEO_URL}"
-    local -r options="-q --no-playlist -t mp3"
+    local -r video_url="${1:?Usage: ${FUNCNAME[0]} VIDEO_URL}"
+    local -ar options=(-q --no-playlist -t mp3)
 
-    yt-dlp $options -o "%(id)s-%(title)s.%(ext)s" "$video_url"
+    yt-dlp "${options[@]}" -o "%(id)s-%(title)s.%(ext)s" "$video_url"
 }
 
 # Download a video file (mp4) from YouTube
 function youtube-download-video
 {
-    local -r video_url="${1:?Usage: $FUNCNAME VIDEO_URL}"
-    local -r options="
+    local -r video_url="${1:?Usage: ${FUNCNAME[0]} VIDEO_URL}"
+    local -ar options=(
         -q --no-playlist
         -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best
-        "
-    yt-dlp $options -o "%(id)s-%(title)s.%(ext)s" "$video_url"
+    )
+    yt-dlp "${options[@]}" -o "%(id)s-%(title)s.%(ext)s" "$video_url"
 }
 
 # Show summary of all items in a play list
 function youtube-playlist-summary
 {
-    local -r playlist_url="${1:?Usage: $FUNCNAME PLAYLIST_URL}"
-    local -r options="--flat-playlist --yes-playlist -J"
+    local -r playlist_url="${1:?Usage: ${FUNCNAME[0]} PLAYLIST_URL}"
+    local -ar options=(
+        --flat-playlist
+        --yes-playlist
+        -J
+    )
 
-    yt-dlp $options "$playlist_url" \
-        | jq -r '.entries[] | ["https://www.youtube.com/watch?v=" + .id, .title, .duration] | @tsv'
+    yt-dlp "${options[@]}" "$playlist_url" |
+        jq -r '.entries[] | ["https://www.youtube.com/watch?v=" + .id, .title, .duration] | @tsv'
 }
 
 # Taken from Advanced Bash-Scripting Guide Appendix M with a small fix
 function extract
 {
-    local archive="$1"
+    local -r archive="$1"
     case $archive in
     *.tar.bz2|*.tbz2)
         tar xvjf "$archive"
@@ -303,7 +315,7 @@ function extract
         7z x "$archive"
         ;;
     *)
-        echo $archive cannot be extracted via $FUNCNAME >&2
+        echo "$archive cannot be extracted via ${FUNCNAME[0]}" >&2
         return 1
         ;;
     esac
@@ -313,49 +325,53 @@ function extract
 function pskill
 {
     # XXX: for suspended processes, 'S' will come to $1 of awk.
-    local pid=$(ps -a -u $USER -W | grep $1 | awk '{ print $1 }')
+    # shellcheck disable=SC2009
+    pid=$(ps -a -u "$USER" -W | grep "$1" | awk '{ print $1 }')
+    local -r pid
     echo -n "killing $1 (process $pid)..."
-    /bin/kill -9 $pid
-    echo "slaughtered."
+    env kill -9 "$pid"
+    echo "slaughtered." >&2
 }
 
 # Reference: info which
 function which
 {
     if [[ -n "$WSL_DISTRO_NAME" ]]; then
-        command which $@
+        command which "$@"
     else
-        { alias ; declare -f ; } | command which \
-            --tty-only --read-alias --read-functions --show-tilde --show-dot $@
+        { alias ; declare -f ; } |
+            command which \
+            --tty-only --read-alias --read-functions --show-tilde --show-dot \
+            "$@"
     fi
 }
 
 function _g++base
 {
-    local -r CPPFLAG="-g -Werror -Wall -Wextra -ansi -pedantic -std=$1"
-    local -r INFILE="${2:?Usage: $FUNCNAME ${1} CPPFILE}"
+    local -ar CPPFLAG=(-g -Werror -Wall -Wextra -ansi -pedantic -std="$1")
+    local -r INFILE="${2:?Usage: ${FUNCNAME[0]} ${1} CPPFILE}"
     local -r OUTFILE=${INFILE%.cpp}
-    g++ $CPPFLAG $INFILE -latomic -o $OUTFILE
+    g++ "${CPPFLAG[@]}" "$INFILE" -latomic -o "$OUTFILE"
 }
 
 function g++11
 {
-    _g++base c++11 $1
+    _g++base c++11 "$1"
 }
 
 function g++14
 {
-    _g++base c++14 $1
+    _g++base c++14 "$1"
 }
 
 function g++17
 {
-    _g++base c++17 $1
+    _g++base c++17 "$1"
 }
 
 function g++20
 {
-    _g++base c++20 $1
+    _g++base c++20 "$1"
 }
 
 # Set the title of the terminal window (or current terminal tab)
@@ -386,23 +402,25 @@ function z
               --color-scale=age --color-scale-mode=gradient \
               --smart-group --time-style=long-iso {2}"
     )
-    test -d "$selected_dir" && builtin cd "$_"
+    test -d "$selected_dir" && builtin cd "$_" || return
 }
 
 # See <https://github.com/junegunn/fzf-git.sh>.
-[ -f "$FZF_GIT_SH" ] && source "$FZF_GIT_SH"
+# shellcheck source=/dev/null
+[[ -f "$FZF_GIT_SH" ]] && source "$FZF_GIT_SH"
 
 if [[ -n "$WSL_DISTRO_NAME" ]]; then
     function pcloud-mount
     {
         local target_drive="P:"
         local mount_point=/mnt/p
-        local uid=$(id -u)
-        local gid=$(id -g)
+        uid=$(id -u)
+        gid=$(id -g)
+        local -r uid gid
 
         sudo mkdir -m 777 -p $mount_point
         sudo chown -R "$USER:${GROUPS[0]}" $mount_point
-        sudo mount -t drvfs $target_drive $mount_point -o metadata,uid=$uid,gid=$gid,umask=22,fmask=11
+        sudo mount -t drvfs $target_drive $mount_point -o "metadata,uid=$uid,gid=$gid,umask=22,fmask=11"
     }
 
     function peek
